// Publishes the survey26 command-line tool on the site: public/survey26.py (the single-file tool)
// and public/survey26-AGENTS.md (the usage guide for coding agents, generated by cli/build_agents_md.py).
import { copyFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
for (const [from, to] of [['survey26.py', 'survey26.py'], ['AGENTS.md', 'survey26-AGENTS.md']]) {
  const source = resolve(root, '..', 'cli', from)
  if (!existsSync(source)) { console.error(`[build-cli] missing ${source}`); process.exit(1) }
  copyFileSync(source, resolve(root, 'public', to))
}
console.log('[build-cli] public/survey26.py and public/survey26-AGENTS.md')
