// Publishes the survey26 command-line tool on the site: public/survey26.py (the single-file tool),
// public/survey26-AGENTS.md (the usage guide for coding agents, generated by cli/build_agents_md.py)
// and public/skills/survey26/SKILL.md (the agent skill, e.g. for ~/.claude/skills/survey26/).
import { copyFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
for (const [from, to] of [['survey26.py', 'survey26.py'], ['AGENTS.md', 'survey26-AGENTS.md'], ['skill/SKILL.md', 'skills/survey26/SKILL.md']]) {
  const source = resolve(root, '..', 'cli', from)
  if (!existsSync(source)) { console.error(`[build-cli] missing ${source}`); process.exit(1) }
  const target = resolve(root, 'public', to)
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(source, target)
}
console.log('[build-cli] public/survey26.py, public/survey26-AGENTS.md and public/skills/survey26/SKILL.md')
