#!/usr/bin/env python3
"""The v4 PRACTICE cards (Practice α β γ δ): their facts and their pages.

    python3 scripts/build-v4-practice-cards.py --facts BUNDLE --card v4-practice-alpha  # write cards/<slug>/card.json
    python3 scripts/build-v4-practice-cards.py --pages          # (re)write web/src/content/taskcard.<id>.v4.*.md
    python3 scripts/build-v4-practice-cards.py --check-pages    # exit 1 if a page differs from its card.json

The practice cards are generated by the organizers from secret seeds; the generator inputs are not
in this repository. Their bundles are fully public once registered (config/, public/ and truth/ in
the 'scenarios' bucket), so participants download the files from the Resources page. What this
repository keeps per card is cards/<slug>/card.json: the facts a card page states (site, season,
nights, targets, regions, fibres, score zero points), read from the registered bundle with --facts,
plus the manifest checksum of that bundle (public.scenarios.checksum). No seed is read or written.

The card pages are rendered from web/src/content/taskcard.template.v4.<lang>.md with those facts and
the per-card story below, so a page can never disagree with its card (tests/test_v4_practice_cards.py
checks it).

Registration (organizer): scenario slug = the card's scenario_slug, contract 'v4-score-v1',
weather/forecasts/events public, global_wallclock_seconds 900; the bundle ZIP as its evaluation
bundle; config/, public/ and truth/ in the public 'scenarios' bucket under <slug>/; parked in the
sealed staging phase until it is linked to practice-projects with its files released.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from challenge import v4_catalog_generator  # noqa: E402

CARDS = ROOT / "cards"
CONTENT = ROOT / "web" / "src" / "content"
SYMBOLS = {"alpha": "α", "beta": "β", "gamma": "γ", "delta": "δ"}

# Per-card wording the facts cannot give: a one-sentence story (en, zh).
STORIES = {
    "alpha": ("A full season at Paranal with only the weather to handle.",
              "帕拉纳尔的一整个季节，只有天气需要应对。"),
    "beta": ("A season from mid-October: the sky moves with the season, and the targets lie in other parts of it.",
             "从十月中旬开始的一季：天空随季节移动，目标分布在天空的其他位置。"),
    "gamma": ("On top of the weather, part of your recent data can be lost once.",
              "除了天气，最近的一部分数据还可能丢失一次。"),
    "delta": ("A larger share of the targets is required, and part of your recent data can be lost once.",
              "必观测目标的比例更高，最近的一部分数据还可能丢失一次。"),
}
# Site names as the pages show them, keyed by the bundle's site name.
SITES = {
    "Paranal, Chile (virtual)": ("Paranal, Chile (virtual)", "智利帕拉纳尔（虚拟站点）"),
}
# The template states these score rules in words; a card that changes them needs new wording.
FIXED_RULES = {("program", "multipliers"): {"DARK": 1.2, "BRIGHT": 1.12, "BACKUP": 1.06},
               ("required", "penalty_per_missing"): 50, ("required", "observed_factor_threshold"): 0.5,
               ("uniformity", "weight"): 200.0, ("reporting", "correct_reward"): 100, ("reporting", "false_penalty"): -150}


def card_files() -> dict[str, Path]:
    """cards/<slug>/card.json of every practice card, by slug."""
    return {path.parent.name: path for path in sorted(CARDS.glob("v4-practice-*/card.json"))}


def facts(card_json: Path) -> dict:
    """What a card page states: cards/<slug>/card.json plus the values derived from it."""
    f = json.loads(card_json.read_text(encoding="utf-8"))
    side = math.isqrt(int(f["fibers"]))
    if side * side != int(f["fibers"]):
        raise ValueError(f"{card_json}: the page wording assumes a square grid")
    return {**f, "grid": side, "field_area": round(int(f["fibers"]) * float(f["fiber_area"]), 6),
            "exposure": tuple(f["exposure"])}


def _rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _footprint_area(root: Path) -> float:
    by: dict[str, list] = {}
    for r in _rows(root / "public" / "footprint.csv"):
        by.setdefault(r["component_id"], []).append((int(r["vertex_index"]), float(r["ra_deg"]), float(r["dec_deg"])))
    total = 0.0
    for verts in by.values():
        pts = [(ra, dec) for _, ra, dec in sorted(verts)]
        units = [v4_catalog_generator._unit_vector(ra, dec) for ra, dec in pts]
        c = v4_catalog_generator._normalize(tuple(sum(v[i] for v in units) for i in range(3)))
        centre = (math.degrees(math.atan2(c[1], c[0])) % 360, math.degrees(math.asin(c[2])))
        total += v4_catalog_generator._polygon_area_deg2(centre, tuple(pts))
    return total


def bundle_facts(root: Path) -> dict:
    """card.json content read from a built bundle (config/, public/; nothing from truth/ but the checksum)."""
    load = lambda rel: json.loads((root / rel).read_text(encoding="utf-8"))  # noqa: E731
    scenario, fiber, score = load("config/v4_scenario.json"), load("config/v4_fiber_config.json"), load("config/v4_score_config.json")
    for keys, expected in FIXED_RULES.items():
        value = score[keys[0]][keys[1]]
        if value != expected:
            raise ValueError(f"{root}: score {'.'.join(keys)} is {value!r}; the page template assumes {expected!r}")
    field = fiber["field"]
    if float(field["gap_deg"]) != 0.0:
        raise ValueError(f"{root}: the page wording assumes fibre cells without gaps")
    nights, targets = _rows(root / "public" / "v4_night_calendar.csv"), _rows(root / "public" / "targets.csv")
    files = sorted(p for p in root.rglob("*") if p.is_file())
    manifest = {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
    site = scenario["site"]
    return {
        "card_id": scenario["task_card"]["card_id"], "slug": scenario["task_card"]["scenario_slug"],
        "phase": scenario["task_card"]["phase"], "stress": bool(scenario["stress"]["enabled"]),
        "wallclock": int(scenario["limits"]["global_wallclock_seconds"]),
        "site": {k: site[k] for k in ("name", "latitude_deg", "longitude_deg")},
        "first_night": nights[0]["night_date"], "last_night": nights[-1]["night_date"], "nights": len(nights),
        "targets": len(targets), "required": sum(r["required"] == "true" for r in targets),
        "regions": len({r["component_id"] for r in _rows(root / "public" / "footprint.csv")}),
        "area": round(_footprint_area(root), -1),
        "sun_limit": float(site.get("sun_altitude_limit_deg", -18.0)), "min_alt": float(scenario["minimum_altitude_deg"]),
        "fibers": int(field["n_fibers"]), "fiber_area": float(field["fiber_area_deg2"]),
        "exposure": [int(fiber["exposure"]["min_duration_seconds"]), int(fiber["exposure"]["max_duration_seconds"])],
        "f0": float(score["flux_zero_point"]), "t0": float(score["exposure_zero_point_seconds"]),
        "checksum": hashlib.sha256(json.dumps(manifest, sort_keys=True).encode()).hexdigest(),
    }


# ------------------------------------------------------------------ pages
def _num(value: float, digits: int = 0) -> str:
    return f"{value:,.{digits}f}"


def _deg(value: float) -> str:
    return f"{value:+.2f}°".replace("+", "" if value >= 0 else "").replace("-", "−")


def _swap(text: str, old: str, new: str) -> str:
    if old not in text:
        raise ValueError(f"template text changed; cannot find {old[:60]!r}")
    return text.replace(old, new)


def render_page(card_json: Path, language: str) -> str:
    f = facts(card_json)
    card_id = f["card_id"]
    symbol = SYMBOLS[card_id]
    zh = language == "zh"
    story = STORIES[card_id][1 if zh else 0]
    template = (CONTENT / f"taskcard.template.v4.{language}.md").read_text(encoding="utf-8")
    text = re.sub(r"\A<!--.*?-->\n\n", "", template, flags=re.S)
    lat, lon = _deg(f["site"]["latitude_deg"]), _deg(f["site"]["longitude_deg"])
    site = SITES[f["site"]["name"]][1 if zh else 0]
    # Worked example: brightness 0.60 and sky quality 0.75 for twice the zero point, so the factor is 0.90.
    zero = f["f0"] * f["t0"]
    long_exposure = round(2 * zero)
    short_factor = 0.60 * long_exposure / 3 * 0.75 / zero
    across = math.sqrt(f["field_area"])
    if zh:
        weather = ("本卡完整的天气和事件文件是公开的（见资源页）。智能体拿不到这些文件：运行中只会逐步收到每 15 分钟一条的简报和大约每周一次的预报。")
        extra = "限时观测请求（`observation_request`）及其结果（`observation_request_result`）。"
        if f["stress"]:
            extra += "另外可能收到一条 `state_resync` 消息。它表示最近的一部分数据丢失了。消息里列出仍然有效的目标和各自的最好得分。请据此重建\"已完成目标\"列表。已经用掉的时间不会退回。"
        try_it = (f"1. 在资源页下载卡片 {symbol}，把卡片文件夹放进项目的 `cards/` 目录。\n"
                  f"2. 运行 `python3 local_runner.py --card cards/{card_id}`。最后一行是你的得分。天气文件是公开的，所以同样的决策在本地和平台上得分相同。\n"
                  f"3. 和 `python3 local_runner.py --card cards/{card_id} --agent examples/idle_agent.py`（什么都不做的智能体）比一比。\n"
                  "4. 修改 `agent/planner.py`，再运行，再比较。\n"
                  f"5. 用 `python3 pack_agent.py --out ../my-agent.zip` 打包，在「参赛」页提交。练习赛会在云端运行全部练习卡 α、β、γ、δ，时间限制同样是 {f['wallclock']} 秒。每日次数见规则页。\n\n"
                  "练习赛成绩只用于练习，不决定奖项。")
        rows = [
            ("| 站点 | 智利帕拉纳尔（虚拟站点）。纬度 −24.62°，经度 −70.40°。 |", f"| 站点 | {site}。纬度 {lat}，经度 {lon}。 |"),
            ("| 仪器 | 16 个光纤可指派方格，排成 4 × 4、无间隙。总面积 6.4 平方度，视场宽约 2.53°。",
             f"| 仪器 | {f['fibers']} 个光纤可指派方格，排成 {f['grid']} × {f['grid']}、无间隙。总面积 {f['field_area']:g} 平方度，视场宽约 {across:.2f}°。"),
            ("太阳低于 −18° 时可以观测", f"太阳低于 {_deg(f['sun_limit']).replace('.00', '')} 时可以观测"),
            ("全程不低于 30° 高度角", f"全程不低于 {f['min_alt']:g}° 高度角"),
            ("你曝光 900 秒。", f"你曝光 {long_exposure} 秒。"),
            ("0.60 × 900 × 0.75 ÷ 450 = 0.90", f"0.60 × {long_exposure} × 0.75 ÷ {zero:g} = 0.90"),
            ("如果只曝光 300 秒，系数只有 0.30。", f"如果只曝光 {long_exposure // 3} 秒，系数只有 {short_factor:.2f}。"),
            ("- 一次曝光变差就报告故障。天气也会让分数变低。\n",
             "- 一次曝光变差就报告故障。天气也会让分数变低。\n- 让智能体读取天气文件。在平台上，智能体只能访问自己的文件夹。\n"),
        ]
    else:
        weather = ("The full weather and event files of this card are public (Resources page). Your agent does not get them: "
                   "during a run it only receives a short bulletin every 15 minutes and a forecast about once a week.")
        extra = "Time-limited observation requests (`observation_request`) and their results (`observation_request_result`)."
        if f["stress"]:
            extra += (" Possibly one `state_resync` message. It means part of your recent data was lost. It lists the targets "
                      "that still count and their best scores. Rebuild your list of finished targets from it. "
                      "The time already spent is not returned.")
        try_it = (f"1. Download card {symbol} from the Resources page and put the card folder into your project's `cards/` folder.\n"
                  f"2. Run `python3 local_runner.py --card cards/{card_id}`. The last line shows your score. The weather files are public, so the same decisions give the same score here and on the platform.\n"
                  f"3. Compare with `python3 local_runner.py --card cards/{card_id} --agent examples/idle_agent.py` (an agent that does nothing).\n"
                  "4. Change `agent/planner.py`, run again, and compare.\n"
                  f"5. Pack with `python3 pack_agent.py --out ../my-agent.zip` and submit it on Participate. Practice runs all practice cards α, β, γ and δ in the cloud, with the same {f['wallclock']} s limit. Daily limits are on the Rules page.\n\n"
                  "Practice scores do not decide awards.")
        rows = [
            ("| Site | Paranal, Chile (virtual). Latitude −24.62°, longitude −70.40°. |", f"| Site | {site}. Latitude {lat}, longitude {lon}. |"),
            ("| Instrument | 16 contiguous fibre assignment cells in a 4 × 4 grid. The field covers 6.4 deg² and is about 2.53° across.",
             f"| Instrument | {f['fibers']} contiguous fibre assignment cells in a {f['grid']} × {f['grid']} grid. The field covers {f['field_area']:g} deg² and is about {across:.2f}° across."),
            ("when the sun is below −18°", f"when the sun is below {_deg(f['sun_limit']).replace('.00', '')}"),
            ("stays at or above 30° altitude", f"stays at or above {f['min_alt']:g}° altitude"),
            ("You expose it for 900 s.", f"You expose it for {long_exposure} s."),
            ("0.60 × 900 × 0.75 ÷ 450 = 0.90", f"0.60 × {long_exposure} × 0.75 ÷ {zero:g} = 0.90"),
            ("With a 300 s exposure the factor is only 0.30.", f"With a {long_exposure // 3} s exposure the factor is only {short_factor:.2f}."),
            ("- Reporting a fault after one bad exposure. Weather also lowers scores.\n",
             "- Reporting a fault after one bad exposure. Weather also lowers scores.\n"
             "- Reading the weather files from your agent. On the platform your agent only has its own folder.\n"),
        ]
    for old, new in rows:
        text = _swap(text, old, new)
    exposure = f"{f['exposure'][0]}–{f['exposure'][1]}"
    text = _swap(text, "60–3600", exposure)
    fields = {
        "SYMBOL": symbol,
        "ONE_SENTENCE_STORY": story, "START_DATE": f["first_night"], "END_DATE": f["last_night"],
        "NIGHTS": str(f["nights"]), "TARGETS": _num(f["targets"]), "AREA_DEG2": _num(f["area"]),
        "REGIONS": str(f["regions"]), "COMPONENTS": str(f["regions"]), "REQUIRED": _num(f["required"]),
        "WALLCLOCK": str(f["wallclock"]), "WEATHER": weather, "EXTRA_MESSAGES": extra, "TRY_IT": try_it,
    }
    text = re.sub(r"\{\{([A-Z_0-9]+)\}\}", lambda m: fields[m.group(1)], text)
    if "{{" in text:
        raise ValueError(f"unfilled template field in {card_id}/{language}")
    return text


def page_path(card_id: str, language: str) -> Path:
    return CONTENT / f"taskcard.{card_id}.v4.{language}.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--facts", type=Path, metavar="BUNDLE", help="write cards/<slug>/card.json from this built bundle")
    parser.add_argument("--card", help="with --facts: the expected scenario slug of the bundle")
    parser.add_argument("--pages", action="store_true", help="write the card pages from cards/*/card.json")
    parser.add_argument("--check-pages", action="store_true", help="fail if a committed page differs from its card.json")
    args = parser.parse_args()
    if args.facts:
        f = bundle_facts(args.facts)
        if args.card and f["slug"] != args.card:
            parser.error(f"{args.facts} is card {f['slug']}, not {args.card}")
        if f["card_id"] not in SYMBOLS or f["phase"] != "practice-projects":
            parser.error(f"{args.facts} is not a practice card ({f['card_id']}, {f['phase']})")
        path = CARDS / f["slug"] / "card.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(f, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(path.relative_to(ROOT).as_posix())
        return 0
    if not (args.pages or args.check_pages):
        parser.error("one of --facts, --pages, --check-pages is required")
    stale = []
    for card_json in card_files().values():
        card_id = facts(card_json)["card_id"]
        for language in ("en", "zh"):
            text, path = render_page(card_json, language), page_path(card_id, language)
            if args.pages:
                path.write_text(text, encoding="utf-8")
            elif not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(ROOT).as_posix())
    if stale:
        print("stale card pages (run --pages):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
